# Introduction 

The broad climate movement and the more specific climate justice movement aim to reshape how governments make policy by drawing attention to climate change and its unequal impacts.
Climate change affects nearly every aspect of life and policy, but climate-relevant policies are inconsistently framed as "climate policy." A major task for climate activists is thus to persuade government officials to see climate change as relevant to their work (from public health and agriculture policy to finance and trade policy). Likewise, nearly all policies have disparate effects, but climate policy is inconsistently framed in distributive justice ("climate justice") terms. Consider two policies made by the U.S. Environmental Protection Agency (EPA) under the authority of the Clean Air Act, one of the main policy tools for U.S. climate policy:

In 2013, the EPA under President Obama published a 22-page draft policy (a "proposed rule") approving the Navajo Nation's plan to to meet the Regional Haze Requirments of the Clean Air Act (including sulfur dioxide, nitrogen oxides, and particulate matter regulations that aim to limit to hazardous ozone pollution). EPA's proposed rule contained no mention of "climate change" and only one brief paragraph on "environmental justice" (concerns about the uneven distribution of environmental harms), asserting that the rule did not have disproportionately high and adverse human health or environmental effects on minority or low-income populations.
In response to 421 public comments citing science showing how rising temperatures would affect ozone formation and raising climate justice concerns, the final rule added nine paragraphs on how EPA was addressing environmental justice concerns but only a brief and dismissive mention of climate change: "climate change is an important issue...[but] regulation of greenhouse gases is conducted under separate statutory requirements from regional haze" (EPA 2013).

In 2017, the EPA under President Trump published a similar 21-page proposed rule approving a Texas plan to meet Regional Haze Requirments. This proposed rule also made no mention of climate change and only a short paragraph on environmental justice concerns. This paragraph only discussed the sulfur dioxide part of the regulations, with no mention of how the policy would affect uneven exposure to pollution related to nitrogen oxides and particulate matter. Again, environmental groups submitted comments citing studies showing how climate change would affect air pollutant concentrations and ozone formation. This rule received 61 comments (still many times the usual level of public attention).
This time, however, EPA made no modifications to the environmental justice section and no mention of climate change in the final rule. 

These examples illustrate several ways in which the policy process may vary. Decades of research have shown that air pollution is unevenly distributed and that its effects will change with a changing climate [@Bernard2001]. Yet, policymakers may or may not see the changing climate or its distributive effects as relevant to their particular tasks and regulations. Many of these tasks are rooted in laws last modified many decades ago that address neither climate change nor environmental justice. Some policymakers and political conditions may be receptive to groups raising climate change or distributive justice concerns, and others may not. This variation in receptivity to scientific and legal claims may have several causes, including policy agendas, institutional cultures, and the scale of public pressure they face. 

When a political leader's policy agenda is hostile to a cause, they and their deputies may ignore activists' demands. For example, the Obama EPA was somewhat responsive to climate and environmental justice concerns while the Trump EPA ignored them. However, presidential agendas do not explain everything: despite the Obama administration's concerns about climate change, many policies that could have incorporated climate science did not. Conversely, despite the Trump administration's general hostility to environmental justice concerns, many Trump-era rules engaged with environmental justice discourse even before commenters demanded it. 

<!--With or without landmark legislation, most U.S. climate policy will continue to be made in dozens of federal agencies, -->
Some government institutions have a longer history of making "climate" policy than others.
Officials at the EPA are exceptionally well-versed in climate change and environmental justice. The EPA makes a great deal of climate-relevant policy and has an Office of Environmental Justice that trains and assists agency staff in incorporating environmental justice into agency actions, including rulemaking. How receptive are other agencies that have not historically been tasked with making climate policy? 

Despite a growing scholarship on the politics of climate policy in the United States, we have little systematic data on the extent to which the issues of climate change and climate justice have gained traction across the vast U.S. bureaucracy. How large of an effect do presidential administrations have on bureaucratic policymaking? 
To what extent do government officials respond to public pressure to address climate change and environmental justice? To what extent does the level of public attention or the scale of public pressure shape whether policymakers engage with or ignore activist demands? 


## Bureaucratic Policymaking is the Terrain of Climate Policy Conflict U.S.

Whether or not it explicitly addresses climate change, nearly all U.S. federal policy relevant to climate change has been made in the executive branch. 
If the U.S. Congress passes major climate legislation, it will require a massive amount of agency rulemaking. A Green New Deal, carbon pricing scheme, or any other legislative initiative would undoubtedly task dozens of agencies with writing and implementing rules. Indeed, the specific legal requirements in agency rules often matter more than the statute itself.
Alternatively, if legislative gridlock continues, U.S. climate policy will continue to be made as it has for decades: by the executive-branch agencies tasked with interpreting and reinterpreting landmark statutes [@Freeman2014]. For example, in just one of many climate-related executive orders, President Obama ordered 30 agencies, from the Army Corps of Engineers to the Department of Agriculture, to make "changes to policies, programs, and regulations...to manage climate risks", leading to thousands of pages of new legal requirements. Presidents Trump and Biden issued subsequent orders to these agencies, leading to thousands of more pages of policy, each dramatically shifting U.S. climate policy.

Agency rulemaking is the primary vehicle by which the executive branch makes policy [@Yackee2009RegGov]. Lobbying the bureaucracy is thus a major way for interest groups to affect the content of public policy [@Yackee2006JPART; @Yackee2019], including regulated businesses [@Gordon2018; @Yackee2006JOP], activists [@Coglianese2001; @whymail], and even legislators [@Judge-Lord2018APSA; @Ritchie2018; @Powell2022]. Like fights over proposed legislation, more frequent fights over proposed rules present key ingredients for organizations to mobilize supporters---perceived political opportunities and a hope that an injustice or threat can be redressed through collective action [@Mcadam2017]. 

<!-- PROBLEM: political scientists have not focused on bureaucratic politics -->

While rulemaking is a major focus of U.S. environmental law scholarship [@Kysar2011; @Ruhl2010; @Freeman2014], political scientists focused on national climate politics in the United States have focused more on electoral politics and legislative policymaking. To the extent that students of American Politics have answered calls to address the climate crisis [@Levin2012; @Javeline2014], they have focused on public opinion [@Guber2013; @Mildenberger2015; @Boussalis2016; @Mildenberger2017; @Merkley2021; @Andrews2021], the emergence of social movements [@Mcadam2017], explaining variation among states and local governments [@Hughes2012; @Stokes2020], and explaining the results of lobbying efforts in Congress [@Skocpol2013; @Grumbach2015; @Brulle2018; @Ganz2019; @Mildenberger2020]. The politics of federal agency rulemaking has been largely overlooked [@Struthers2021].^[Notable exceptions include case studies of the EPA <!--@Cook2013, @Cook2014,--> [@Cook2013; @Cook2017; @Cook2018], Regulatory Impact Analyses [@Costa2015; @Costa2019], and state-level rulemaking [@Crow2015; @Crow2019]. I discuss these in further detail below.] <!--, and @Rios2020 on ej-->

<!--gap: selection on the DV-->
Furthermore, research on the politics of climate policymaking has focused on policies that are already framed as climate policy. Policy failures are critical to theory development and empirically neglected [@Stokes2020]. The failure to consider climate change in policymaking is an important type of failure and one that will not be captured if scholars focus on policy processes that are already framed as climate policy. Likewise, in order to study the effects of growing movements that demand attention to distributive justice, policymakers' failures to address distributive impacts are as important as cases where a policy does address distributive justice concerns. 

Case selection is a major challenge in assessing the impact of advocacy campaigns. @Leech2010 argues that the influence of advocacy campaigns is overstated because scholars focus on issues where impact is especially likely---issues characterized by a lot of advocacy and recent or impending policy change. @Lowery2013 raises the opposite concern---that high-salience issues that scholars select are the cases least likely to observe advocacy success. In short, studies often select cases on the dependent variable. While large-scale and longitudinal studies have become more common [@Hojnacki2012], systematic impact across the thousands of non-landmark policies that governments make every year is rarely the dependent variable.

<!--gap: mechanisms--->
Finally, while public opinion and political communication scholars have made great progress in identifying how people form preferences for climate policy, the mechanisms by which public opinion translates into public pressure and then into public policy are less clear.
A lack of public pressure is a well-known cause of legislative failure [@Skocpol2013], but scholars have paid less attention to the role of public pressure in bureaucratic policymaking. Institutional features of the U.S. federal legislative process empower carbon-intensive industries [@Grumbach2015]. Similar institutional advantages may exist in the administrative state [@Yackee2006JOP; @Carpenter2021]. We also know that coalitions of businesses and labor block climate legislation [@Mildenberger2020]. These same coalitions may also shape bureaucratic policymaking, but we lack systematic data on who lobbies and who wins in bureaucratic policymaking.


<!--this paper-->


This paper begins to fill these gaps by providing a systematic look across thousands of policies that do and do not address climate change and climate justice. I exploit this variation to assess the extent to which policy documents change (or fail to change) in response to public comments raising climate and climate justice issues. I also assess the effect of the general level of public attention and scale of public pressure to address climate change and climate justice. Assessing rates of responsiveness across agencies and over time, I provide novel estimates of the extent to which the climate and climate justice movements have gained traction in the policy process and the extent to which government responsiveness varies across agencies and presidential administrations.

In addition to statistical analysis of agency responsiveness to public comments, I offer a descriptive account of the groups that most often advance climate and climate justice policy demands and mobilize public pressure behind these demands. Who is engaging and mobilizing is essential context for any study of the effects of public input. Examining who participates tells us who is empowered by the policy process and who is left out.

I find that most U.S. Federal Agencies rarely addressed climate change and almost never addressed climate justice concerns. From 2005 to 2020, less than 8% of relevant agency rules addressed climate change, and only 2% addressed climate justice, despite growing activist demand.
In contrast, 20 percent of all public comments received by the agencies in this study mentioned climate change. 
Among climate activism targeting federal agencies, however, the climate justice movement is small. Only 8% of comments mentioning climate change also mention climate justice or environmental justice. Furthermore, nearly all public comments raising climate justice concerns were mobilized by just five national advocacy groups. 

Assessing responsiveness across thousands of draft and final agency rules, I find that raising climate change or climate justice concerns increases the probability that they will be addressed in the final rule. Greater levels of public pressure behind climate advocacy efforts and general public attention both increase the likelihood of that climate change and climate justice will be addressed in final rules. However, policymakers are much more responsive to concerns about climate change than environmental justice or climate justice.
Across specifications, low-profile policies are more likely to change in response to public pressure. 

These results have implications for policy and advocacy. First, these findings highlight low compliance executive orders instructing agencies to incorporate climate and environmental justice into agency decisions.
Baseline levels of attention to climate change and climate justice at most agencies are extremely low. Rates of responsiveness to comments raising these concerns are also low. For advocates, these results highlight opportunities to shape policymaking both by providing technical information and by mobilizing political pressure. 