# Theory

My analysis of the politics of climate policy focuses on organized groups and the information they provide to policymakers.

## Interest Groups

Organized groups are the key actors in American politics, especially technocratic policymaking.
As @Hacker2021 observe,

>"[The United States'] institutional terrain advantages political actors with the capacity to work across multiple venues, over extended periods, and in a political environment where coordinated government action is difficult, and strategies of evasion and exit from regulatory constraints are often successful. These capacities are characteristic of organized groups, not individual voters."

While scholars have made great progress in studying the determinants and evolution of public opinion on climate change [@Mildenberger2015; @Boussalis2016], to study particular policy fights, organized groups are the key actors that shape policy proposals, mobilize support, and pressure policymakers.

## Information as the Currency of Lobbying

### Technical Information

Dominant theories of bureaucratic policymaking focus on how agencies learn about policy problems and solutions [@Kerwin2011]. Leading formal models are information-based models where sophisticated lobbying groups affect policy by revealing information to the agency [@Gailmard2017;@Libgober2018], and empirical studies support the conclusion that information is the currency of lobbying in rulemaking [@Yackee2012;@Cook2017;@Gordon2018;@Walters2019].  

Agency rulemaking is an especially technocratic and legalistic form of policymaking that explicitly privileges scientific and legal facts as the appropriate basis for decisions.  Procedural requirements to consider relevant information create incentives for lobbying groups to overwhelm agencies with complex technical information, making rulemaking obscure to all but the most well-informed insiders [@Wagner2010]. <!--Empirical work shows Yackee -->
Influence in rulemaking generally requires resources and technical expertise [@Yackee2019].

<!--As @Yackee2019 notes:

> "to be influential during rulemaking,
commenters may require resources and technical expertise.
> As Epstein, Heidt, and Farina (2014) suggest, agency rule-writers---who are often chosen because
of their technical or policy-specific expertise---privilege the type of data-driven
arguments and reasoning that are not common to citizen comments." (p. 10)

-->

The result is that rulemaking is dominated by sophisticated and well-resourced interest groups capable of providing new technical or legal information. Empirical scholarship finds that economic elites and business groups
dominate American politics in general [@Jacobs2005; @Soss2007; @Hertel-Fernandez2019; @Hacker2003; @Gilens2014] and rulemaking in
particular<!--. While some are optimistic that requirements for agencies to
solicit and respond to public comments on proposed rules allow "civil
society" to provide public oversight [@Michaels2015; @Metzger2010], most
studies find that participants in rulemaking often represent elites and
business interests--> [@Seifter2016UCLA; @Crow2015; @Wagner2011; @West2009; @Yackee2006JOP; @Yackee2006JPART; @Golden1998; @Haeder2015; @Cook2017; @LibgoberCarpenter2018]. To the extent that scholars address public pressure campaigns, both
existing theory and empirical scholarship suggest skepticism that public pressure campaigns matter. For example, @Balla2018 find that  "legal imperatives trump political considerations" (p. 1). (See Chapter \@ref(whymail) and Chapter \@ref(influence) for reviews of scholarship on mass comment campaigns and their impact on policy.) 
My analysis in Chapter \@ref(influence) also shows no clear relationship between public pressure and lobbying success. Causes that directly confront elite and business interests, like the environmental justice movement, may be especially unlikely to influence bureaucratic policymaking. Alternatively, it is also possible that some social movements have normative and political resources sufficient to overcome the technocratic biases of bureaucratic policymaking.

### Political Information

Existing information-based theories of bureaucratic policymaking have little room for social movements and political pressure.
While social movement organizations do engage in fights over technical reports and scientific studies, the information that activists provide is often more overtly political. 
As discussed in Chapter \@ref(whymail), @Nelson2012
identify political information as a potentially influential result of
groups expanding their lobbying coalition. While they focus on
mobilizing experts, they describe a dynamic that can be extended
to mobilizing public pressure:
<!-- 
> "strategic recruitment, we theorize, mobilizes new actors to participate in the policymaking process, bringing with them novel technical and political information. In other words, when an expanded strategy is employed, leaders activate individuals and organizations to participate in the policymaking process who, without the coordinating efforts of the leaders, would otherwise not lobby. This activation is important because it implies that -->

> coalition lobbying can generate new information and new actors---beyond simply the 'usual suspects' ---relevant to policy decisionmakers. (p. 343)

Expanding on the arguments about the potential value of political information advanced in Chapter \@ref(whymail),
I argue that mobilizing new actors to participate in the policymaking process may yield information about a policy's disparate effects. Information about a policy's disparate effects is an additional form of political information.
Like levels of public attention and pressure, the normative appeal of distributive justice claims can be a political resource, potentially allowing groups to change policymakers' perceptions of their political environment and the political consequences of their decisions. 

#### Information About a Policy's Disparate Effects

<!-- lowi politics -->
The politics and outcomes of policymaking depend on how the relevant groups are defined [@Lowi1964].  <!--TODO-->
While specific *data* on disparate impacts of policy may require expertise [@Ganz2019], anyone can highlight a community of concern or potential distributive effects of a policy. Identifying communities of concern is a political statement that does not require technical expertise. Just as @Nelson2012 found regarding mobilizing diverse experts, mobilizing diverse communities affected by a policy may introduce new claims from new actors about how the communities that a policy may benefit or harm should be constructed. 

Informing policymakers about how a particular set of stakeholders will be affected can be a lobbying tactic. Distributive justice claims simultaneously assert that a particular group deserves specific attention and demand that the policymaker account for how that group may be impacted, both of which may require revisions to the policy. Likewise, an organization may tell policymakers what a key constituency or affected groups think about the proposed policy---for example, whether they support or oppose the policy.  Instead of bolstering *scientific* claims, such comments that focus on a policy's disparate impacts bolster *political* claims about who counts and even *who exists* as a distinct, potentially affected group that deserves policymakers' attention. 

The political construction of policy-relevant groups through the policy process has long interested administrative law scholars. @Gellhorn1972 argues that "individuals and groups willing to assist administrative agencies in identifying interests deserving protection" (p. 403) improve the policy process. @Seifter2016UCLA argues that policymaker's beliefs about who is lobbying them and who those groups represent ought to be (and likely is) key to how they respond.


<!-- institutions feinstein -->
The power of groups to affect policy depends on their recognition by formal and informal institutions. All organizations systematically privilege some policy problems, solutions, and types of information over others.

> All forms of political organization have a bias in favor of the exploitation of some kinds of conflict and the suppression of others because organization is the mobilization of bias. Some issues are organized into politics, while others are organized out. [@Schattschneider1975, p. 71]

Public comment periods in agency rulemaking are formally more "identity neutral" than policy processes with procedural rights reserved for certain interests [@Feinstein2021]. This means that the political construction of relevant groups depends on who participates and the identities they mobilize or claim to represent. As @Yackee2019 and others note, the information costs mean that individuals rarely participate. Instead, groups claim to represent various constituencies. "Because the costs of individualized participation in policy decision making are often excessive, informal representatives are prevalent as a form of participation in agency decisions" [@Rossi1997, p. 194].




<!--CBA-->
Bureaucratic policymaking in the United States is dominated by cost-benefit analysis, which requires defining groups that are benefited or harmed by a policy and may even weigh or prioritize benefits or costs to certain groups. Agencies have many reasons to consider the distributional effects of policy and often do. For example, President Biden issued a memorandum instructing the Director of the Office of Management and Budget to propose recommendations for "procedures that take into account the distributional consequences of regulations." <!--[CITE https://www.theregreview.org/2021/04/26/adler-factoring-equity-benefit-cost-analysis/]-->
Thus, comments raising distributive concerns provide potentially influential political information.

This distributive information raises claims of distributive justice. 
Public comment periods are celebrated as "a crucial way to ensure that agency decisions are legitimate, accountable, and just" [@Bierschbach2012, p. 20]. "Public participation can force agencies to rethink initial inclinations" [@Seifter2016UCLA, p. 1329]---such as which social groups are relevant or deserve special attention.
Courts purportedly review policy decisions made through rulemaking with a particular eye toward whether they foster "fairness and deliberation" (*United States v. Mead Corp.*, 2001) and occasionally note the volume or diversity of participants in the public comment process (e.g., *Vermont Yankee v. NRDC*, 1978). While there is mixed empirical evidence about the importance of policy processes for judicial review, the number of public comments received on a draft policy is associated with courts letting the final agency policy stand [@judgelord2016MPSA]. Despite the dominance of business groups and seeming lack of success for public pressure campaigns in general, claims of distributive justice may have a unique role in bureaucratic policymaking. 


#### Public Pressure as a Political Resource

The chances that an agency will address distributive justice claims may be affected by other political factors, including the overall levels of public attention or public pressure. 
As theorized in Chapter \@ref(influence), the number of supporters may
matter because it indicates support among relevant communities or the broader public. Again, instead of bolstering *scientific* claims, perceived levels of public support bolster *political* claims. 
<!--
Like other forms of political participation, such as protests and letter-writing campaigns, 
public pressure campaigns provide no new technical information. <!--%In this sense, they are not useful. 
Nor do they wield any formal authority to reward or sanction bureaucrats.
The number on each side, be it ten or ten million, has no legal import for an agency's response.
However,
--> 
An organization's ability to expand the scope of conflict by mobilizing
a large number of people can be a valuable political resource [@Schattschneider1975]. <!--@Furlong1997 and @Kerwin2011
identify mobilization as a tactic. The organizations they surveyed
believed that forming coalitions and mobilizing large numbers of people
were among the most effective lobbying tactics. While @Furlong1997 and @Kerwin2011 focused on how
organizations mobilize their members, I expand on this understanding of mobilization as a lobbying tactic to include a campaign's broader audience, more akin to the concept of
an attentive public [@Key1961] or issue public [@Converse1964]. 
-->

I argue in Chapter \@ref(whymail) that interest groups and their lobbying coalitions are the proper units of analysis, and individual participants are best understood as measuring an amplitude of support for their efforts.
While scholars often *compare* the participation of groups from individual citizens (see @Yackee2019 for a review), "it can be difficult to distinguish an individual's independent contribution from an interest-group-generated form letter" [@Seifter2016UCLA, pg. 1313].  As [@Rossi1997, p. 194] argues, "individuals are most likely to participate in agency decisions
by virtue of their membership in interest groups." Indeed, as I demonstrated in Chapter \@ref(whymail), nearly all individual comments on proposed policies are mobilized by interest groups. Researchers should view the participation of individuals as a direct result of interest group mobilization and can ignore the small number of unaffiliated individuals. <!--Indeed, efforts to broaden citizen participation that seek *unmediated* participation are likely infeasible.--> 

Because many politically active groups are "memberless" or run by professionals who lobby with little input from their members [@Baumgartner2001; @Skocpol2003; @Schlozman2012], evidence of an actual constituency is valuable political information. Petition signatures and form letters are among the only ways a pressure group can demonstrate an engaged and issue-specific constituency on whose behalf they claim to advocate. While lobbying disclosure requirements could provide other information about how well groups represent the constituencies they claim to represent [@Seifter2016UCLA], letter-writing campaigns are one of the only strategies currently available to demonstrate issue-specific congruence between the positions of groups and the people they claim to represent.<!-- [@judgelord2019SPSA].-->

Finally, building on the distinction between direct and indirect influence set out in Chapter \@ref(whymail), expanding the scope of conflict by mobilizing public attention to rulemaking may shift policymakers' attention away from the technical information provided by the "usual suspects" and toward the distributive effects of policy. The "fire alarm" role that interest groups play in the policy process [@McCubbins1984] may have different effects when sounding the alarm also involves "going public."

## Political Control 

While carbon-intensive sectors have secured representation in both major political parties [@Mildenberger2020],
opponents to policies addressing climate change have increasingly aligned themselves with the Republican party [@Stokes2020; @Powell2022].


## Institutional Biases

"The federal Surface Mining Control and Reclamation Act was structured initially and then became amplified through policy feedback processes, to support coal production over other values" [@Bozzi2013].

## Public Pressure

### Who organizes public pressure and why? 

#### Conflict expansion 

Organizing public pressure has long been understood as a tactic that disadvantaged intersts use to improve their chances of winning [@Schnattsneider]. 

#### Astroturf

Recent studies in the policy space have called the conclusion that conflict expansion is a tacktic of the less powerful. 
Powerful fossil fuel companies have used public public pressure campaigns to [@Stokes2020, p. 46, 66]
To what extent does public pressure in rulemaking resemble public voice or "astroturf?"

<!--
> "groups **construct** public opinion both by working with the public and by creating fake public campaigns through astroturfing." (p. 46). 

> “the public is often a **tool** that advocates and opponents use to try to influence decision-makers.”

> “the public’s **voice** can be heard through organizing and activism. Still, in contemporary American policymaking, interest groups’ voices are usually much louder than the public’s. Increasingly, the public is used as a **tool** by interest groups in their battles over policy.”
(p. 66).


#### Astroturf and conflict expansion

> “The opponents relied heavily on fake grassroots campaigns—sometimes called “astroturfing”—while advocates tried to bolster and communicate genuine support from rural and Republican parts of the state. Interest groups on **both sides** aimed to expand the scope of conflict.”

> “Opponent interest groups can simultaneously deploy all of these **direct and indirect** strategies. When **better-resourced** opponents continually attack a policy, policy retrenchment can occur by a thousand cuts. (p. 66)

Hertle-Fernandez & Stokes vs. Schattschneider?!?

---> 





