---
title: The Climate Movement's Impact on Technocratic Policymaking
subtitle:
anonymous: false
author:
- name: Devin Judge-Lord
  affiliation: Harvard University
  footnote: "I will be grateful for any feedback: [DevinJudgeLord@fas.harvard.edu](mailto:DevinJudgeLord@fas.harvard.edu). Slides and the most recent draft are available at <https://judgelord.github.io/research/cj>. This paper has benefited from funding from the National Science Foundation and American Political Science Association."
date: "`r Sys.Date()`"
warning: "NOTE: This short paper is the quantative portion of a paper that will eventually include hand-coded coalitions and lobbying success. The theory and methods are more fully developed in my dissertation chapters on [public pressure campaigns](https://judgelord.github.io/research/whymail) and the [environmental justice movement](https://judgelord.github.io/research/ej)." # Additional tables, figures, and replication code are available at <https://judgelord.github.io/cj/cj-appendix.html>.
abstract: | 
  `r readLines(here::here("docs", "cj-abstract.text"))`
bibliography: '`r here::here("assets/dissertation.bib")`'
biblio-style: '`r here::here("assets/apsr.bst")`'
link-citations: yes
citecolor: black
urlcolor: blue
frontpage: true
spacing: onehalfspacing
# github-repo: https://github.com/judgelord/dissertation
# description: ""
# keywords: Interest groups, rulemaking, lobbying, bureaucratic politics, data sources

output:
    bookdown::pdf_document2:
      template: '../assets/article-template.tex' # redirect to assets 
      keep_tex: true
      latex_engine: xelatex
      citation_package: natbib
      toc: false
      fig_caption: true
      fig.topcaption: true
      fig.width: 7
    word_document: default
header-includes:
  - \usepackage{floatrow}
  - \usepackage{float}
  - \floatsetup[figure]{capposition=top}
  - \floatsetup[table]{capposition=top}
---

```{r global.options, include=FALSE}
source(here::here("code", "setup.R"))
library(tidyverse)
library(magrittr)
       
options(knitr.graphics.auto_pdf = TRUE)

knitr::opts_chunk$set(echo = FALSE, 
                      cache = FALSE, 
                      fig.align = 'center',
                      fig.width = 7,
                      out.width = "6.5in",
                      fig.path= "figs/",
                      fig.show = "hold",
                      warning=FALSE, 
                      message=FALSE)
```


\thispagestyle{empty}

<!--
\singlespacing

\centerline{\textbf{\underline{NOTE TO READER}}}
The following chapter is part of a dissertation exploring the effects of public pressure on agency rulemaking, a technocratic policy process where “public participation” is usually limited to sophisticated lobbying but occasionally includes millions of people mobilized by public pressure campaigns. Public comment periods on proposed policies purport to provide democratic accountability. Yet theories of bureaucratic policymaking largely ignore the occasional bursts of civic engagement that generate the vast majority of public comments on proposed rules. To fill this gap, I build and test theories about the role of public pressure in policymaking. I collect and analyze millions of public comments to develop the first systematic measures of civic engagement and influence in bureaucratic policymaking. The outline of the dissertation is as follows:  

```{ child = here::here("outline.md")}
```

-->



\newpage

\onehalfspacing

\setcounter{page}{1}


```{r child = "01-cj-intro.Rmd"}
```

```{r child = "02-cj-theory.Rmd"}
```

```{r child = "03-cj-data.Rmd"}
```

```{r child = "04-cj-results.Rmd"}
```
